In [2]:
import numpy as np

In [3]:
from sklearn.linear_model import LinearRegression

In [4]:
model = LinearRegression()
np.random.seed(42)
X = 2 * np.random.rand(100, 2)
w_true = np.array([[3],[3]])
y = 2 +  X @ w_true + np.random.randn(100, 1) 

In [5]:
from sklearn.linear_model import SGDRegressor

sgd_reg = SGDRegressor(
    max_iter=1000,      # number of epochs
    learning_rate='constant',
    eta0=0.01           # learning rate
)
sgd_reg.fit(X, y) 

/opt/anaconda3/lib/python3.12/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SGDRegressor(learning_rate='constant')

In [6]:
test_X = np.array([[1, 1], [2, 2]])
sgd_reg.predict(test_X)

array([ 8.17959948, 14.46737386])

In [7]:
model = LinearRegression()
model.fit(X,y)

LinearRegression()

In [8]:
model.predict(test_X)

array([[ 8.11907867],
       [14.46588507]])

In [9]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
import numpy as np

np.random.seed(42)
    
# Generate non-linear data: y = 3x^2 + 2x + 1 + noise
X = np.linspace(-3, 3, 100)
X = X.reshape(-1,1)
y = 3 * X**2 + 2 * X + 1 + np.random.randn(100) * 2


test_X = np.array([-2, 0, 2])
test_X = test_X.reshape(-1,1)

poly = PolynomialFeatures(degree=2, include_bias=True)
X_poly = poly.fit_transform(X)
test_X = poly.transform(test_X)

model = LinearRegression()
model.fit(X_poly, y)

LinearRegression()

In [10]:
model.predict(test_X)

array([[ 9.99342831e+00,  8.72347140e+00,  1.02953771e+01,
         1.20460597e+01,  8.53169325e+00,  8.53172609e+00,
         1.21584256e+01,  1.05348695e+01,  8.06105123e+00,
         1.00851201e+01,  8.07316461e+00,  8.06854049e+00,
         9.48392454e+00,  5.17343951e+00,  5.55016433e+00,
         7.87542494e+00,  6.97433776e+00,  9.62849467e+00,
         7.18395185e+00,  6.17539260e+00,  1.19312975e+01,
         8.54844740e+00,  9.13505641e+00,  6.15050363e+00,
         7.91123455e+00,  9.22184518e+00,  6.69801285e+00,
         9.75139604e+00,  7.79872262e+00,  8.41661250e+00,
         7.79658678e+00,  1.27045564e+01,  8.97300555e+00,
         6.88457814e+00,  1.06450898e+01,  6.55831270e+00,
         9.41772719e+00,  5.08065975e+00,  6.34362790e+00,
         9.39372247e+00,  1.04769332e+01,  9.34273656e+00,
         8.76870344e+00,  8.39779261e+00,  6.04295602e+00,
         7.56031158e+00,  8.07872246e+00,  1.11142445e+01,
         9.68723658e+00,  5.47391969e+00,  9.64816794e+0

In [11]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
import numpy as np

np.random.seed(42)

# 1. Generate data
X = np.linspace(-3, 3, 100).reshape(-1,1)
y = 3 * X**2 + 2 * X + 1 + np.random.randn(100) * 2

# 2. Define test points
test_X = np.array([[-2], [0], [2]])

# 3. Polynomial features
poly = PolynomialFeatures(degree=2, include_bias=True)
X_poly = poly.fit_transform(X)
test_X_poly = poly.transform(test_X)

# 4. Train model
model = LinearRegression()
model.fit(X_poly, y)

# 5. Predict on test points
predictions = model.predict(test_X_poly)
print(predictions)


[[ 9.99342831e+00  8.72347140e+00  1.02953771e+01  1.20460597e+01
   8.53169325e+00  8.53172609e+00  1.21584256e+01  1.05348695e+01
   8.06105123e+00  1.00851201e+01  8.07316461e+00  8.06854049e+00
   9.48392454e+00  5.17343951e+00  5.55016433e+00  7.87542494e+00
   6.97433776e+00  9.62849467e+00  7.18395185e+00  6.17539260e+00
   1.19312975e+01  8.54844740e+00  9.13505641e+00  6.15050363e+00
   7.91123455e+00  9.22184518e+00  6.69801285e+00  9.75139604e+00
   7.79872262e+00  8.41661250e+00  7.79658678e+00  1.27045564e+01
   8.97300555e+00  6.88457814e+00  1.06450898e+01  6.55831270e+00
   9.41772719e+00  5.08065975e+00  6.34362790e+00  9.39372247e+00
   1.04769332e+01  9.34273656e+00  8.76870344e+00  8.39779261e+00
   6.04295602e+00  7.56031158e+00  8.07872246e+00  1.11142445e+01
   9.68723658e+00  5.47391969e+00  9.64816794e+00  8.22983544e+00
   7.64615600e+00  1.02233526e+01  1.10619990e+01  1.08625602e+01
   7.32156495e+00  8.38157525e+00  9.66252686e+00  1.09510903e+01
   8.04165

## Training Neural Network on MNIST

In [13]:
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

# Load full MNIST
mnist = fetch_openml('mnist_784', version=1, as_frame=False)
X, y = mnist["data"], mnist["target"].astype(int)

# Normalize pixel values
X = X / 255.0

# Split into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=5000, train_size=50000, random_state=42)

# One-hot encode labels
encoder = OneHotEncoder(sparse_output=False)
y_train_onehot = encoder.fit_transform(y_train.reshape(-1,1))
y_test_onehot = encoder.transform(y_test.reshape(-1,1))


In [14]:
X_train.shape

(50000, 784)

In [15]:
X_test.shape

(5000, 784)

In [16]:
y_test.shape

(5000,)

### SGD

In [18]:
from neural_network import NeuralNetwork 

nn = NeuralNetwork(layer_sizes=[784, 64, 10], activation='relu', optimizer='sgd' )

In [19]:
nn.fit(X_train, y_train_onehot, learning_rate=0.01, epochs=500)

Epoch    0 | Loss: 0.330318 | Accuracy: 0.9000
Epoch   10 | Loss: 0.317804 | Accuracy: 0.9000
Epoch   20 | Loss: 0.308046 | Accuracy: 0.9000
Epoch   30 | Loss: 0.299298 | Accuracy: 0.9000
Epoch   40 | Loss: 0.290880 | Accuracy: 0.9000
Epoch   50 | Loss: 0.282506 | Accuracy: 0.9000
Epoch   60 | Loss: 0.274141 | Accuracy: 0.9000
Epoch   70 | Loss: 0.265802 | Accuracy: 0.9000
Epoch   80 | Loss: 0.257536 | Accuracy: 0.9003
Epoch   90 | Loss: 0.249387 | Accuracy: 0.9008
Epoch  100 | Loss: 0.241390 | Accuracy: 0.9017
Epoch  110 | Loss: 0.233589 | Accuracy: 0.9030
Epoch  120 | Loss: 0.226022 | Accuracy: 0.9048
Epoch  130 | Loss: 0.218717 | Accuracy: 0.9072
Epoch  140 | Loss: 0.211709 | Accuracy: 0.9097
Epoch  150 | Loss: 0.205027 | Accuracy: 0.9123
Epoch  160 | Loss: 0.198673 | Accuracy: 0.9150
Epoch  170 | Loss: 0.192654 | Accuracy: 0.9181
Epoch  180 | Loss: 0.186966 | Accuracy: 0.9212
Epoch  190 | Loss: 0.181600 | Accuracy: 0.9242
Epoch  200 | Loss: 0.176546 | Accuracy: 0.9271
Epoch  210 | 

In [20]:
y_pred_proba = nn.predict_proba(X_test) # Predict probabilities
y_pred = np.argmax(y_pred_proba, axis=1) # Pick class with highest probability
y_true = np.argmax(y_test_onehot, axis=1)

# Accuracy
accuracy = np.mean(y_pred == y_true)
print("Test Accuracy:", accuracy)

Test Accuracy: 0.8452


## Adam 

In [22]:
nn = NeuralNetwork(layer_sizes=[784, 64, 10], activation='relu', optimizer='adam' )
nn.fit(X_train, y_train_onehot, learning_rate=0.01, epochs=500)

Epoch    0 | Loss: 0.339672 | Accuracy: 0.9000
Epoch   10 | Loss: 0.070614 | Accuracy: 0.9758
Epoch   20 | Loss: 0.052269 | Accuracy: 0.9826
Epoch   30 | Loss: 0.041891 | Accuracy: 0.9864
Epoch   40 | Loss: 0.034977 | Accuracy: 0.9887
Epoch   50 | Loss: 0.030161 | Accuracy: 0.9904
Epoch   60 | Loss: 0.026666 | Accuracy: 0.9916
Epoch   70 | Loss: 0.023868 | Accuracy: 0.9924
Epoch   80 | Loss: 0.021521 | Accuracy: 0.9932
Epoch   90 | Loss: 0.019529 | Accuracy: 0.9940
Epoch  100 | Loss: 0.017801 | Accuracy: 0.9946
Epoch  110 | Loss: 0.016292 | Accuracy: 0.9951
Epoch  120 | Loss: 0.014968 | Accuracy: 0.9955
Epoch  130 | Loss: 0.013786 | Accuracy: 0.9959
Epoch  140 | Loss: 0.012711 | Accuracy: 0.9963
Epoch  150 | Loss: 0.011740 | Accuracy: 0.9967
Epoch  160 | Loss: 0.010852 | Accuracy: 0.9969
Epoch  170 | Loss: 0.010039 | Accuracy: 0.9972
Epoch  180 | Loss: 0.009295 | Accuracy: 0.9974
Epoch  190 | Loss: 0.008606 | Accuracy: 0.9977
Epoch  200 | Loss: 0.007964 | Accuracy: 0.9979
Epoch  210 | 

In [41]:
y_pred_proba = nn.predict_proba(X_test) # Predict probabilities
y_pred = np.argmax(y_pred_proba, axis=1) # Pick class with highest probability
y_true = np.argmax(y_test_onehot, axis=1)

# Accuracy
accuracy = np.mean(y_pred == y_true)
print("Test Accuracy:", accuracy)

Test Accuracy: 0.9638


## Nadam

In [43]:
nn = NeuralNetwork(layer_sizes=[784, 64, 10], activation='relu', optimizer='nadam' )
nn.fit(X_train, y_train_onehot, learning_rate=0.01, epochs=100)

Epoch    0 | Loss: 0.347745 | Accuracy: 0.9000
Epoch   10 | Loss: 0.078128 | Accuracy: 0.9743
Epoch   20 | Loss: 0.054821 | Accuracy: 0.9815
Epoch   30 | Loss: 0.045844 | Accuracy: 0.9846
Epoch   40 | Loss: 0.039878 | Accuracy: 0.9869
Epoch   50 | Loss: 0.035782 | Accuracy: 0.9882
Epoch   60 | Loss: 0.031735 | Accuracy: 0.9897
Epoch   70 | Loss: 0.028771 | Accuracy: 0.9907
Epoch   80 | Loss: 0.026311 | Accuracy: 0.9917
Epoch   90 | Loss: 0.024757 | Accuracy: 0.9921


In [ ]:
y_pred_proba = nn.predict_proba(X_test) # Predict probabilities
y_pred = np.argmax(y_pred_proba, axis=1) # Pick class with highest probability
y_true = np.argmax(y_test_onehot, axis=1)

# Accuracy
accuracy = np.mean(y_pred == y_true)
print("Test Accuracy:", accuracy)

In [45]:
nn = NeuralNetwork(layer_sizes=[784, 128, 64, 10], activation='relu', optimizer='adam' )
nn.fit(X_train, y_train_onehot, learning_rate=0.01, epochs=100)

Epoch    0 | Loss: 0.334117 | Accuracy: 0.9000
Epoch   10 | Loss: 0.073568 | Accuracy: 0.9749
Epoch   20 | Loss: 0.046764 | Accuracy: 0.9843
Epoch   30 | Loss: 0.034972 | Accuracy: 0.9882
Epoch   40 | Loss: 0.027752 | Accuracy: 0.9907
Epoch   50 | Loss: 0.022742 | Accuracy: 0.9926
Epoch   60 | Loss: 0.018931 | Accuracy: 0.9938
Epoch   70 | Loss: 0.015938 | Accuracy: 0.9950
Epoch   80 | Loss: 0.013491 | Accuracy: 0.9958
Epoch   90 | Loss: 0.011475 | Accuracy: 0.9965


In [47]:
y_pred_proba = nn.predict_proba(X_test) # Predict probabilities
y_pred = np.argmax(y_pred_proba, axis=1) # Pick class with highest probability
y_true = np.argmax(y_test_onehot, axis=1)

# Accuracy
accuracy = np.mean(y_pred == y_true)
print("Test Accuracy:", accuracy)

Test Accuracy: 0.9646


## AdamW

In [49]:
nn = NeuralNetwork(layer_sizes=[784, 128, 64, 10], activation='relu', optimizer='adamw' )
nn.fit(X_train, y_train_onehot, learning_rate=0.01, epochs=100)

Epoch    0 | Loss: 0.335118 | Accuracy: 0.9000
Epoch   10 | Loss: 0.069484 | Accuracy: 0.9765
Epoch   20 | Loss: 0.045154 | Accuracy: 0.9850
Epoch   30 | Loss: 0.032661 | Accuracy: 0.9892
Epoch   40 | Loss: 0.025320 | Accuracy: 0.9916
Epoch   50 | Loss: 0.020324 | Accuracy: 0.9934
Epoch   60 | Loss: 0.016642 | Accuracy: 0.9947
Epoch   70 | Loss: 0.013746 | Accuracy: 0.9957
Epoch   80 | Loss: 0.011390 | Accuracy: 0.9965
Epoch   90 | Loss: 0.009466 | Accuracy: 0.9973


In [51]:
y_pred_proba = nn.predict_proba(X_test) # Predict probabilities
y_pred = np.argmax(y_pred_proba, axis=1) # Pick class with highest probability
y_true = np.argmax(y_test_onehot, axis=1)

# Accuracy
accuracy = np.mean(y_pred == y_true)
print("Test Accuracy:", accuracy)

Test Accuracy: 0.966


## AdaGrad

In [53]:
nn = NeuralNetwork(layer_sizes=[784, 128, 64, 10], activation='relu', optimizer='adagrad' )
nn.fit(X_train, y_train_onehot, learning_rate=0.01, epochs=100)

Epoch    0 | Loss: 0.333178 | Accuracy: 0.9000
Epoch   10 | Loss: 0.066864 | Accuracy: 0.9778
Epoch   20 | Loss: 0.043382 | Accuracy: 0.9855
Epoch   30 | Loss: 0.031431 | Accuracy: 0.9895
Epoch   40 | Loss: 0.024744 | Accuracy: 0.9919
Epoch   50 | Loss: 0.019653 | Accuracy: 0.9937
Epoch   60 | Loss: 0.015815 | Accuracy: 0.9949
Epoch   70 | Loss: 0.012840 | Accuracy: 0.9960
Epoch   80 | Loss: 0.010524 | Accuracy: 0.9968
Epoch   90 | Loss: 0.008663 | Accuracy: 0.9975


In [54]:
y_pred_proba = nn.predict_proba(X_test) # Predict probabilities
y_pred = np.argmax(y_pred_proba, axis=1) # Pick class with highest probability
y_true = np.argmax(y_test_onehot, axis=1)

# Accuracy
accuracy = np.mean(y_pred == y_true)
print("Test Accuracy:", accuracy)

Test Accuracy: 0.9686


## Adamax

In [55]:
nn = NeuralNetwork(layer_sizes=[784, 128, 64, 10], activation='relu', optimizer='adamax' )
nn.fit(X_train, y_train_onehot, learning_rate=0.01, epochs=100)

Epoch    0 | Loss: 0.335663 | Accuracy: 0.9000
Epoch   10 | Loss: 0.069322 | Accuracy: 0.9761
Epoch   20 | Loss: 0.047236 | Accuracy: 0.9842
Epoch   30 | Loss: 0.037889 | Accuracy: 0.9875
Epoch   40 | Loss: 0.031939 | Accuracy: 0.9896
Epoch   50 | Loss: 0.027774 | Accuracy: 0.9910
Epoch   60 | Loss: 0.024548 | Accuracy: 0.9921
Epoch   70 | Loss: 0.021899 | Accuracy: 0.9930
Epoch   80 | Loss: 0.019665 | Accuracy: 0.9938
Epoch   90 | Loss: 0.017738 | Accuracy: 0.9944


In [56]:
y_pred_proba = nn.predict_proba(X_test) # Predict probabilities
y_pred = np.argmax(y_pred_proba, axis=1) # Pick class with highest probability
y_true = np.argmax(y_test_onehot, axis=1)

# Accuracy
accuracy = np.mean(y_pred == y_true)
print("Test Accuracy:", accuracy)

Test Accuracy: 0.9608


## RMSProp

In [57]:
nn = NeuralNetwork(layer_sizes=[784, 128, 64, 10], activation='relu', optimizer='rmsprop' )
nn.fit(X_train, y_train_onehot, learning_rate=0.001, epochs=100)y_pred_proba = nn.predict_proba(X_test) # Predict probabilities


Epoch    0 | Loss: 0.340721 | Accuracy: 0.9000
Epoch   10 | Loss: 0.159094 | Accuracy: 0.9370
Epoch   20 | Loss: 0.077417 | Accuracy: 0.9736
Epoch   30 | Loss: 0.071405 | Accuracy: 0.9747
Epoch   40 | Loss: 0.054780 | Accuracy: 0.9819
Epoch   50 | Loss: 0.118011 | Accuracy: 0.9618
Epoch   60 | Loss: 0.056470 | Accuracy: 0.9797
Epoch   70 | Loss: 0.039979 | Accuracy: 0.9862
Epoch   80 | Loss: 0.026954 | Accuracy: 0.9911
Epoch   90 | Loss: 0.040979 | Accuracy: 0.9863


In [69]:
y_pred = np.argmax(y_pred_proba, axis=1) # Pick class with highest probability
y_true = np.argmax(y_test_onehot, axis=1)

# Accuracy
accuracy = np.mean(y_pred == y_true)
print("Test Accuracy:", accuracy)

Test Accuracy: 0.9608


## Momentum

In [73]:
nn = NeuralNetwork(layer_sizes=[784, 128, 64, 10], activation='relu', optimizer='momentum' )
nn.fit(X_train, y_train_onehot, learning_rate=0.01, epochs=100)


Epoch    0 | Loss: 0.339600 | Accuracy: 0.9000
Epoch   10 | Loss: 0.304934 | Accuracy: 0.9000
Epoch   20 | Loss: 0.264660 | Accuracy: 0.9012
Epoch   30 | Loss: 0.207242 | Accuracy: 0.9136
Epoch   40 | Loss: 0.153879 | Accuracy: 0.9410
Epoch   50 | Loss: 0.119209 | Accuracy: 0.9581
Epoch   60 | Loss: 0.098867 | Accuracy: 0.9672
Epoch   70 | Loss: 0.086538 | Accuracy: 0.9719
Epoch   80 | Loss: 0.078505 | Accuracy: 0.9748
Epoch   90 | Loss: 0.072939 | Accuracy: 0.9765


In [78]:
y_pred = np.argmax(y_pred_proba, axis=1) # Pick class with highest probability
y_true = np.argmax(y_test_onehot, axis=1)

# Accuracy
accuracy = np.mean(y_pred == y_true)
print("Test Accuracy:", accuracy)

Test Accuracy: 0.9608
