In [66]:
import numpy as np

In [67]:
from sklearn.linear_model import LinearRegression

In [68]:
model = LinearRegression()
np.random.seed(42)
X = 2 * np.random.rand(100, 2)
w_true = np.array([[3],[3]])
y = 2 +  X @ w_true + np.random.randn(100, 1) 

In [69]:
from sklearn.linear_model import SGDRegressor

sgd_reg = SGDRegressor(
    max_iter=1000,      # number of epochs
    learning_rate='constant',
    eta0=0.01           # learning rate
)
sgd_reg.fit(X, y) 

/opt/anaconda3/lib/python3.12/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SGDRegressor(learning_rate='constant')

In [70]:
test_X = np.array([[1, 1], [2, 2]])
sgd_reg.predict(test_X)

array([ 8.17959948, 14.46737386])

In [71]:
model = LinearRegression()
model.fit(X,y)

LinearRegression()

In [72]:
model.predict(test_X)

array([[ 8.11907867],
       [14.46588507]])

In [73]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
import numpy as np

np.random.seed(42)
    
# Generate non-linear data: y = 3x^2 + 2x + 1 + noise
X = np.linspace(-3, 3, 100)
X = X.reshape(-1,1)
y = 3 * X**2 + 2 * X + 1 + np.random.randn(100) * 2


test_X = np.array([-2, 0, 2])
test_X = test_X.reshape(-1,1)

poly = PolynomialFeatures(degree=2, include_bias=True)
X_poly = poly.fit_transform(X)
test_X = poly.transform(test_X)

model = LinearRegression()
model.fit(X_poly, y)

LinearRegression()

In [74]:
model.predict(test_X)

array([[ 9.99342831e+00,  8.72347140e+00,  1.02953771e+01,
         1.20460597e+01,  8.53169325e+00,  8.53172609e+00,
         1.21584256e+01,  1.05348695e+01,  8.06105123e+00,
         1.00851201e+01,  8.07316461e+00,  8.06854049e+00,
         9.48392454e+00,  5.17343951e+00,  5.55016433e+00,
         7.87542494e+00,  6.97433776e+00,  9.62849467e+00,
         7.18395185e+00,  6.17539260e+00,  1.19312975e+01,
         8.54844740e+00,  9.13505641e+00,  6.15050363e+00,
         7.91123455e+00,  9.22184518e+00,  6.69801285e+00,
         9.75139604e+00,  7.79872262e+00,  8.41661250e+00,
         7.79658678e+00,  1.27045564e+01,  8.97300555e+00,
         6.88457814e+00,  1.06450898e+01,  6.55831270e+00,
         9.41772719e+00,  5.08065975e+00,  6.34362790e+00,
         9.39372247e+00,  1.04769332e+01,  9.34273656e+00,
         8.76870344e+00,  8.39779261e+00,  6.04295602e+00,
         7.56031158e+00,  8.07872246e+00,  1.11142445e+01,
         9.68723658e+00,  5.47391969e+00,  9.64816794e+0

In [75]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
import numpy as np

np.random.seed(42)

# 1. Generate data
X = np.linspace(-3, 3, 100).reshape(-1,1)
y = 3 * X**2 + 2 * X + 1 + np.random.randn(100) * 2

# 2. Define test points
test_X = np.array([[-2], [0], [2]])

# 3. Polynomial features
poly = PolynomialFeatures(degree=2, include_bias=True)
X_poly = poly.fit_transform(X)
test_X_poly = poly.transform(test_X)

# 4. Train model
model = LinearRegression()
model.fit(X_poly, y)

# 5. Predict on test points
predictions = model.predict(test_X_poly)
print(predictions)


[[ 9.99342831e+00  8.72347140e+00  1.02953771e+01  1.20460597e+01
   8.53169325e+00  8.53172609e+00  1.21584256e+01  1.05348695e+01
   8.06105123e+00  1.00851201e+01  8.07316461e+00  8.06854049e+00
   9.48392454e+00  5.17343951e+00  5.55016433e+00  7.87542494e+00
   6.97433776e+00  9.62849467e+00  7.18395185e+00  6.17539260e+00
   1.19312975e+01  8.54844740e+00  9.13505641e+00  6.15050363e+00
   7.91123455e+00  9.22184518e+00  6.69801285e+00  9.75139604e+00
   7.79872262e+00  8.41661250e+00  7.79658678e+00  1.27045564e+01
   8.97300555e+00  6.88457814e+00  1.06450898e+01  6.55831270e+00
   9.41772719e+00  5.08065975e+00  6.34362790e+00  9.39372247e+00
   1.04769332e+01  9.34273656e+00  8.76870344e+00  8.39779261e+00
   6.04295602e+00  7.56031158e+00  8.07872246e+00  1.11142445e+01
   9.68723658e+00  5.47391969e+00  9.64816794e+00  8.22983544e+00
   7.64615600e+00  1.02233526e+01  1.10619990e+01  1.08625602e+01
   7.32156495e+00  8.38157525e+00  9.66252686e+00  1.09510903e+01
   8.04165

In [76]:
import numpy as np

class NeuralNetwork:
    def __init__(self, layer_sizes, activation='relu'):
        """
        layer_sizes: list of layer sizes [input, hidden1, hidden2, ..., output]
        Example: [2, 4, 3, 1] = 2 inputs, 2 hidden layers (4 and 3 neurons), 1 output
        """
        self.layer_sizes = layer_sizes
        self.num_layers = len(layer_sizes)
        self.activation_name = activation

        # Initialize weights and biases
        self.weights = []
        self.biases = []

        # He initialization for better convergence
        for i in range(self.num_layers - 1):
            w = np.random.randn(layer_sizes[i], layer_sizes[i+1]) * np.sqrt(2 / layer_sizes[i])
            b = np.zeros((1, layer_sizes[i + 1]))

            self.weights.append(w)
            self.biases.append(b)
        self.z_values = []
        self.a_values = [] 
    
    def relu(self, z):
        return np.maximum(0, z)
    
    def relu_derivative(self, z):
        return (z > 0).astype(float)
    
    def sigmoid(self, z): 
        return 1 / (1 + np.exp(-np.clip(z, -500, 500)))
    
    def sigmoid_derivative(self, z):
        s = self.sigmoid(z)
        return s * (1 - s)
    
    def tanh(self, z):
        return np.tanh(z)
    
    def tanh_derivative(self, z):
        return 1 - np.tanh(z) ** 2
    
    def softmax(self, z):
        exp_z = np.exp(z - np.max(z, axis=1, keepdims=True))
        return exp_z / np.sum(exp_z, axis=1, keepdims=True)
    
    def activate(self, z):
        if self.activation_name == 'relu':
            return self.relu(z)
        elif self.activation_name == 'sigmoid':
            return self.sigmoid(z)
        elif self.activation_name == 'tanh':
            return self.tanh(z)
        else:
            return z
        
    def activate_derivative(self, z):
        if self.activation_name == 'relu':
            return self.relu_derivative(z)
        elif self.activation_name == 'sigmoid':
            return self.sigmoid_derivative(z)
        elif self.activation_name == 'tanh':
            return self.tanh_derivative(z)
        else:
            return np.ones_like(z)
        
    def forward(self, X):
        self.z_values = []
        self.a_values = [X]
        a = X
        for i in range(self.num_layers - 1):
            z = a @ self.weights[i] + self.biases[i]
            self.z_values.append(z)

            if i < self.num_layers - 2:
                a = self.activate(z)
            else:
                a = self.softmax(z)
            self.a_values.append(a)

        return a
    
    def backward(self, X, y, learning_rate):
        m = X.shape[0]

        dW = [None] * (self.num_layers - 1)
        dB = [None] * (self.num_layers - 1)

        dz = self.a_values[-1] - y
        for i in range(self.num_layers - 2, -1, -1):
            dW[i] = (1/m) * (self.a_values[i].T @ dz)
            dB[i] = (1/m) * np.sum(dz, axis=0, keepdims=True)

            if i > 0:
                da = dz @ self.weights[i].T   # Propagates the gradient one layer backward
                dz = da * self.activate_derivative(self.z_values[i-1])

        for i in range(self.num_layers - 1):
            self.weights[i] -= learning_rate * dW[i]
            self.biases[i] -= learning_rate * dB[i]
        
        

    def fit(self, X, y, learning_rate=0.01, epochs=100, verbose=True):
        if X.ndim == 1:
            X = X.reshape(-1, 1)
        if y.ndim == 1:
            y = y.reshape(-1, 1)
        for epoch in range(epochs):
            y_pred = self.forward(X)
            y_clipped = np.clip(y_pred, 1e-7, 1 - 1e-7)
            loss = -np.mean(y * np.log(y_clipped) + 
                           (1 - y) * np.log(1 - y_clipped))
            self.backward(X,y, learning_rate)
            if verbose and epoch % 10 == 0:
                    accuracy = np.mean((y_pred > 0.5).astype(int) == y)
                    print(f"Epoch {epoch:4d} | Loss: {loss:.6f} | Accuracy: {accuracy:.4f}")
    def predict_proba(self,X):
        if X.ndim == 1:
            X = X.reshape(-1, 1)
        return self.forward(X)
    def predict(self, X, threshold=0.5):
        proba = self.predict_proba(X)
        return (proba > threshold).astype(int)
  

In [77]:
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

# Load full MNIST
mnist = fetch_openml('mnist_784', version=1, as_frame=False)
X, y = mnist["data"], mnist["target"].astype(int)

# Normalize pixel values
X = X / 255.0

# Split into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=5000, train_size=50000, random_state=42)

# One-hot encode labels
encoder = OneHotEncoder(sparse_output=False)
y_train_onehot = encoder.fit_transform(y_train.reshape(-1,1))
y_test_onehot = encoder.transform(y_test.reshape(-1,1))


In [78]:
X_train.shape

(50000, 784)

In [79]:
X_test.shape

(5000, 784)

In [80]:
y_test.shape

(5000,)

In [81]:
nn = NeuralNetwork(layer_sizes=[784, 64, 10], activation='relu')

In [82]:
nn.fit(X_train, y_train_onehot, learning_rate=0.01, epochs=500)

Epoch    0 | Loss: 0.330318 | Accuracy: 0.9000
Epoch   10 | Loss: 0.317804 | Accuracy: 0.9000
Epoch   20 | Loss: 0.308046 | Accuracy: 0.9000
Epoch   30 | Loss: 0.299298 | Accuracy: 0.9000
Epoch   40 | Loss: 0.290880 | Accuracy: 0.9000
Epoch   50 | Loss: 0.282506 | Accuracy: 0.9000
Epoch   60 | Loss: 0.274141 | Accuracy: 0.9000
Epoch   70 | Loss: 0.265802 | Accuracy: 0.9000
Epoch   80 | Loss: 0.257536 | Accuracy: 0.9003
Epoch   90 | Loss: 0.249387 | Accuracy: 0.9008
Epoch  100 | Loss: 0.241390 | Accuracy: 0.9017
Epoch  110 | Loss: 0.233589 | Accuracy: 0.9030
Epoch  120 | Loss: 0.226022 | Accuracy: 0.9048
Epoch  130 | Loss: 0.218717 | Accuracy: 0.9072
Epoch  140 | Loss: 0.211709 | Accuracy: 0.9097
Epoch  150 | Loss: 0.205027 | Accuracy: 0.9123
Epoch  160 | Loss: 0.198673 | Accuracy: 0.9150
Epoch  170 | Loss: 0.192654 | Accuracy: 0.9181
Epoch  180 | Loss: 0.186966 | Accuracy: 0.9212
Epoch  190 | Loss: 0.181600 | Accuracy: 0.9242
Epoch  200 | Loss: 0.176546 | Accuracy: 0.9271
Epoch  210 | 

In [83]:
# Predict probabilities
y_pred_proba = nn.predict_proba(X_test)

# Pick class with highest probability
y_pred = np.argmax(y_pred_proba, axis=1)

# True labels
y_true = np.argmax(y_test_onehot, axis=1)

# Accuracy
accuracy = np.mean(y_pred == y_true)
print("Test Accuracy:", accuracy)

Test Accuracy: 0.8452
