In [10]:
import numpy as np

In [4]:
from sklearn.linear_model import LinearRegression

In [22]:
model = LinearRegression()
np.random.seed(42)
X = 2 * np.random.rand(100, 2)
w_true = np.array([[3],[3]])
y = 2 +  X @ w_true + np.random.randn(100, 1) 

In [24]:
from sklearn.linear_model import SGDRegressor

sgd_reg = SGDRegressor(
    max_iter=1000,      # number of epochs
    learning_rate='constant',
    eta0=0.01           # learning rate
)
sgd_reg.fit(X, y) 

/opt/anaconda3/lib/python3.12/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SGDRegressor(learning_rate='constant')

In [26]:
test_X = np.array([[1, 1], [2, 2]])
sgd_reg.predict(test_X)

array([ 8.17959948, 14.46737386])

In [28]:
model = LinearRegression()
model.fit(X,y)

LinearRegression()

In [30]:
model.predict(test_X)

array([[ 8.11907867],
       [14.46588507]])

In [27]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
import numpy as np

np.random.seed(42)
    
# Generate non-linear data: y = 3x^2 + 2x + 1 + noise
X = np.linspace(-3, 3, 100)
X = X.reshape(-1,1)
y = 3 * X**2 + 2 * X + 1 + np.random.randn(100) * 2


test_X = np.array([-2, 0, 2])
test_X = test_X.reshape(-1,1)

poly = PolynomialFeatures(degree=2, include_bias=True)
X_poly = poly.fit_transform(X)
test_X = poly.transform(test_X)

model = LinearRegression()
model.fit(X_poly, y)

LinearRegression()

In [31]:
model.predict(test_X)

array([[ 9.99342831e+00,  8.72347140e+00,  1.02953771e+01,
         1.20460597e+01,  8.53169325e+00,  8.53172609e+00,
         1.21584256e+01,  1.05348695e+01,  8.06105123e+00,
         1.00851201e+01,  8.07316461e+00,  8.06854049e+00,
         9.48392454e+00,  5.17343951e+00,  5.55016433e+00,
         7.87542494e+00,  6.97433776e+00,  9.62849467e+00,
         7.18395185e+00,  6.17539260e+00,  1.19312975e+01,
         8.54844740e+00,  9.13505641e+00,  6.15050363e+00,
         7.91123455e+00,  9.22184518e+00,  6.69801285e+00,
         9.75139604e+00,  7.79872262e+00,  8.41661250e+00,
         7.79658678e+00,  1.27045564e+01,  8.97300555e+00,
         6.88457814e+00,  1.06450898e+01,  6.55831270e+00,
         9.41772719e+00,  5.08065975e+00,  6.34362790e+00,
         9.39372247e+00,  1.04769332e+01,  9.34273656e+00,
         8.76870344e+00,  8.39779261e+00,  6.04295602e+00,
         7.56031158e+00,  8.07872246e+00,  1.11142445e+01,
         9.68723658e+00,  5.47391969e+00,  9.64816794e+0

In [33]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
import numpy as np

np.random.seed(42)

# 1. Generate data
X = np.linspace(-3, 3, 100).reshape(-1,1)
y = 3 * X**2 + 2 * X + 1 + np.random.randn(100) * 2

# 2. Define test points
test_X = np.array([[-2], [0], [2]])

# 3. Polynomial features
poly = PolynomialFeatures(degree=2, include_bias=True)
X_poly = poly.fit_transform(X)
test_X_poly = poly.transform(test_X)

# 4. Train model
model = LinearRegression()
model.fit(X_poly, y)

# 5. Predict on test points
predictions = model.predict(test_X_poly)
print(predictions)


[[ 9.99342831e+00  8.72347140e+00  1.02953771e+01  1.20460597e+01
   8.53169325e+00  8.53172609e+00  1.21584256e+01  1.05348695e+01
   8.06105123e+00  1.00851201e+01  8.07316461e+00  8.06854049e+00
   9.48392454e+00  5.17343951e+00  5.55016433e+00  7.87542494e+00
   6.97433776e+00  9.62849467e+00  7.18395185e+00  6.17539260e+00
   1.19312975e+01  8.54844740e+00  9.13505641e+00  6.15050363e+00
   7.91123455e+00  9.22184518e+00  6.69801285e+00  9.75139604e+00
   7.79872262e+00  8.41661250e+00  7.79658678e+00  1.27045564e+01
   8.97300555e+00  6.88457814e+00  1.06450898e+01  6.55831270e+00
   9.41772719e+00  5.08065975e+00  6.34362790e+00  9.39372247e+00
   1.04769332e+01  9.34273656e+00  8.76870344e+00  8.39779261e+00
   6.04295602e+00  7.56031158e+00  8.07872246e+00  1.11142445e+01
   9.68723658e+00  5.47391969e+00  9.64816794e+00  8.22983544e+00
   7.64615600e+00  1.02233526e+01  1.10619990e+01  1.08625602e+01
   7.32156495e+00  8.38157525e+00  9.66252686e+00  1.09510903e+01
   8.04165